### ISSUE TITLE
Problem on rounding

### ISSUE THREAD

**Issue by bybybybyb** [vighneshbirodkar/dating_game#5]
Hi,

I think it is not correct to directly use string format to round the numbers. It will round the fraction up if it is larger than 0.5, which will cause false positive on some cases.

As an example, if my Person change 0.09 to 0.1071, then the actual ratio of change = (0.1071 - 0.09) / 0.09 = 0.19, but as string format will round 0.1071 to 0.11, the ratio of change detected by architech.py will becomes (0.11 - 0.09) / 0.09 = 0.22.

A possible solution is to cast the input float with the process num = int(num * 100) / 100.0, which will remove digits after the second digit right to the decimal point.

Also, please cast the number to integers before the comparison at line 174 person.py. I even encountered:

![capture](https://cloud.githubusercontent.com/assets/2519878/20285659/1c56b13a-aa91-11e6-923a-6b032e83aaa9.PNG)

in the screenshot the array printed is the result of
`percent_change = np.abs(delta_wegiths/self.initial_weights)`

Please do remember direct float comparison is dangerous.

**Comment by vighneshbirodkar** [comment]
Regarding your first point, if the person wants to set the value `0.1071`, it is really not clear what the team's assumption is. They might want round it off to `0.10` or `0.11`. If the original weight was more than `0.09`, `0.11` would be a valid number. And I think for this case you can easily make a change in your client.

For your 2nd query, I am waiting for the professors response for this thread
https://groups.google.com/forum/#!topic/hps-csci-ga2965-001/gBY7wF0H9hE

**Comment by bybybybyb** [comment]
I agree with you on the first point and I did fix it in my code. But it makes the functions you wrote in utils.py for convenience be useless, which is a pity.

The thread seems irrelevant with the second problem. The second problem is caused by direct comparison among floating points. I think the second problem can be solved by enlarge the number by 100 and cast it to int to get rid of the decimal point as well as making it be an integer comparison.

By the way, Prof. Shasha replied me by e-mail, saying there would be like 100 attributes so the number of weights that a Person can alter is no longer a problem; but he didn't mention whether the balancing process also counts for the the number of weights modified. Maybe you could send him another e-mail to clarify it.

Sincerely,
Boyuan

**Comment by vighneshbirodkar** [comment]
> But it makes the functions you wrote in utils.py for convenience be useless, which is a pity.

I don't think that's the case. Because the case you pointed out is a specific case where lowering the number was the right thing to do, that may not always be the case. What if the team had a strategy in which a higher weight would give them an advantage ? If the team's original weight was `0.90` and then they passed `0.915`. Should I round to `0.91` or `0.92` ? You can choose either strategy, neither one of them is right or wrong, it entirely depends on the team. And the point of the util functions was to conform to the message format, I don't claim that they do the optimal rounding.

I misunderstood your second problem. I see it now. Could you maybe send me a small example with `n=5` ? I am looking for the values of `delta_weights` and `initial_weights` which caused this.

edit: I am aware that floating point equality comparisons are dangerous, but why should this issue arise with `>`. It'll be interesting to see the values.

**Comment by vighneshbirodkar** [comment]
@ylns1314 It would be helpful if you could print `weights` and `self.initial_weights` as well

**Comment by bybybybyb** [comment]
Generally all ratio approaching 0.2 or -0.2 will cause the problem. For example:
![qq 20161114222439](https://cloud.githubusercontent.com/assets/2519878/20292142/28e5d1ec-aab9-11e6-9f1b-35e033d1b2ab.png)

**Comment by bybybybyb** [comment]
I also printed the value of percent_change > 0.2:
![qq 20161114222439](https://cloud.githubusercontent.com/assets/2519878/20292360/fd3aed32-aaba-11e6-8c1d-6bf3d4b15050.png)

**Comment by vighneshbirodkar** [comment]
@ylns1314 You are right. I made the changes according to your suggestion. That should fix the issue

**Comment by bybybybyb** [comment]
Great. Thank you.

**Comment by bybybybyb** [comment]
Well, it is still a floating point comparison... What I suggested is you could use integer comparison, which means enlarge it by 100 and cast to integer and then compare with 20, without decimal points. As you finally still store the value in a floating point and compare with 0.2 (which is also a floating point), the problem will still occur sometimes.

You can find more information about the problem from http://floating-point-gui.de/errors/comparison/

**Comment by vighneshbirodkar** [comment]
The latest commit should do it

**Comment by bybybybyb** [comment]
Seems good.
